name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v4

      # Set up Conda (use miniconda for more control)
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          conda-version: 'latest'
          environment-file: environment.yml
          python-version: '3.10'
          auto-activate-base: false  # Prevents activation of base environment
          
      # Cache Conda dependencies to speed up the build process
      - name: Cache Conda dependencies
        uses: actions/cache@v3
        with:
          path: ~/.conda
          key: ${{ runner.os }}-conda-${{ hashFiles('**/environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      # Install dependencies using Conda environment
      - name: Install dependencies
        run: conda env update --file environment.yml --name myenv

      # Activate the conda environment
      - name: Activate environment
        run: conda activate myenv

      # Lint with flake8 (configured via environment.yml)
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # Test with pytest (with parallelization)
      - name: Test with pytest
        run: |
          pytest --maxfail=3 --disable-warnings --max-complexity=10 --tb=short
